### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by Teoc99** [MrPnut/SpotifyWPF#5]
Error: Setup has detected that the file 'C:\Users\**\AppData\Local\Temp\VSD98A6.tmp\DotNetFX472\NDP472-KB4054531-Web.exe' has changed since it was initially published.

**Comment by MrPnut** [comment]
Hi @Teoc99,

Does it work if you clean your temporary files?  Try running "Disk Cleanup" (cleanmgr.exe) and removing temporary files

**Comment by Teoc99** [comment]
Thanks for the suggestion. Unfortunately, I still get the same error message when I try to install.

**Comment by MrPnut** [comment]
I updated the installer to be msix vs clickonce.
I also added a zip file release that can just be extracted anywhere and ran.
